In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df=pd.read_csv("boston.csv")

In [4]:
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [5]:
df.describe()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [6]:
df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [7]:
df.tail()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [8]:
df.head(10)

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
5,0.02985,0.0,2.18,0,0.458,6.430,58.7,6.0622,3,222,18.7,394.12,5.21,28.7
6,0.08829,12.5,7.87,0,0.524,6.012,66.6,5.5605,5,311,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0,0.524,6.172,96.1,5.9505,5,311,15.2,396.90,19.15,27.1
8,0.21124,12.5,7.87,0,0.524,5.631,100.0,6.0821,5,311,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,0,0.524,6.004,85.9,6.5921,5,311,15.2,386.71,17.10,18.9

In [9]:
df.tail(10)

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
496,0.28960,0.0,9.69,0,0.585,5.390,72.9,2.7986,6,391,19.2,396.90,21.14,19.7
497,0.26838,0.0,9.69,0,0.585,5.794,70.6,2.8927,6,391,19.2,396.90,14.10,18.3
498,0.23912,0.0,9.69,0,0.585,6.019,65.3,2.4091,6,391,19.2,396.90,12.92,21.2
499,0.17783,0.0,9.69,0,0.585,5.569,73.5,2.3999,6,391,19.2,395.77,15.10,17.5
500,0.22438,0.0,9.69,0,0.585,6.027,79.7,2.4982,6,391,19.2,396.90,14.33,16.8
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [10]:
df.isnull()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,False,False,False,False,False,False,False,False,False,False,False,False,False,False
502,False,False,False,False,False,False,False,False,False,False,False,False,False,False
503,False,False,False,False,False,False,False,False,False,False,False,False,False,False
504,False,False,False,False,False,False,False,False,False,False,False,False,False,False
505,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [11]:
df.notnull()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,True,True,True,True,True,True,True,True,True,True,True,True,True,True
502,True,True,True,True,True,True,True,True,True,True,True,True,True,True
503,True,True,True,True,True,True,True,True,True,True,True,True,True,True
504,True,True,True,True,True,True,True,True,True,True,True,True,True,True
505,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [12]:
df.isnull().sum()

crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
medv       0
dtype: int64

In [13]:
X=df[['crim','zn','indus','chas','nox','rm','age','dis','rad','tax','ptratio','b','lstat']]
Y=df['medv']

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [15]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.4,random_state=42)

In [16]:
X_train.shape

(303, 13)

In [17]:
X_test.shape

(203, 13)

In [18]:
Y_train.shape

(303,)

In [19]:
Y_test.shape

(203,)

In [20]:
lrobject=LinearRegression()

In [21]:
lrobject.fit(X_train,Y_train)

LinearRegression()

In [22]:
Y_prediction=lrobject.predict(X_test)

In [23]:
Y_prediction

array([28.70025691, 37.27542414, 14.45066349, 25.73435643, 18.49763912,
       22.76561878, 17.11890368, 13.48208813, 22.54968769, 20.55427051,
       24.89964971, 17.95378789, -6.25387186, 21.45751485, 19.24359044,
       25.88484249, 20.03562327,  5.43649759, 40.51846823, 17.25804397,
       27.97547423, 30.52428232, 10.62579589, 24.13957256, 17.9691631 ,
       15.70456146, 23.13185264, 14.47022575, 22.38985994, 19.37080505,
       22.24020037, 25.33048308, 25.11428577, 18.622199  , 16.09804981,
       17.56608944, 30.84772682, 20.52366567, 24.21685764, 25.12389018,
       13.87545879, 32.08576418, 42.69334232, 17.57356292, 27.18664139,
       17.00879858, 13.65816821, 26.32678962, 19.85072475, 30.22451992,
       20.89326788, 34.32273159, 15.30429383, 26.09067695, 39.54965618,
       22.78325442, 18.64595069, 33.48386781, 24.94968103, 12.43100969,
       22.47035481, 30.85432505, 32.1854089 , 16.87897756, 20.67775641,
       16.56514522, 20.02974058, 26.41085611, 31.55334393, 12.01236966,
       20.5755039 , 27.2101929 , 10.84119438, 16.94886713, 23.819897  ,
        5.41829661, 21.34860257, 41.46811322, 17.89184792,  8.55598713,
       21.22643245, 12.55281823, 21.60873562,  9.23301292, 23.01327607,
       32.40354417, 18.838331  , 25.84079392, 29.68609136, 19.67664041,
       25.86395856,  5.77415108, 19.85173596, 14.85755383, 14.78530087,
       20.54331883, 24.79552215, -0.38128645, 13.86239885, 15.56058277,
       22.22723166, 24.50054142, 10.53570651, 19.94505871, 23.7931239 ,
       11.98747478, 18.6702269 , 25.90367796, 21.28160063, 24.63144222,
        7.57729972, 18.74553016, 22.18842892, 27.6454184 , 32.11389939,
       15.44169788, 34.29613564, 12.93746053, 21.31348928, 28.78086431,
       15.52254246, 24.96278456,  4.69457295, 23.80013757, 26.24973178,
       23.33054233, 25.28572597, 33.43479966, 21.26605693, 38.31882195,
       13.57250428, 25.35725719, 17.63235356, 20.24489731,  9.59365733,
       21.15392804, 22.76713792, 32.33731713, 31.76032874, 15.22252164,
       16.76008974, 29.08091493, 25.09803633, 16.78722207,  6.55837627,
       26.51952996, 23.64255121, 17.06446945, 13.06111281, 39.57174946,
       16.63358238, 18.06625285, 25.38864599, 23.58406741, 22.44180986,
       21.762737  , 16.71391675, 23.31074519, 29.09428383,  7.28647565,
       24.30936529, 17.1913895 , 21.18924966, 25.29277028, 28.17616874,
       20.74427938, 40.59250988, 18.6287946 , 15.12541523, 18.29850858,
       17.15651918, 22.43515912, 23.64679216, 33.40316974, 22.40547942,
       20.28211069, 25.2413554 , 31.47695469, 33.39153046, 28.43793741,
        8.541879  ,  4.85267978, 12.42580604, 20.41598522, 36.05885172,
       33.43770529, 15.81380686,  3.26964909, 33.70613701, 21.80595258,
       19.16226992, 26.12924528, 18.61875414, 17.76686204, 11.01275111,
       32.47158925, 24.70737227, 19.49374868, 19.3662591 , 11.5366082 ,
       28.982763  , 21.74478698, 32.57522994])

In [27]:
from sklearn import metrics

In [28]:
metrics.mean_absolute_error(Y_test,Y_prediction)

3.2979696834924352

In [29]:
metrics.mean_squared_error(Y_test,Y_prediction)

21.832709989577562

In [30]:
np.sqrt(metrics.mean_squared_error(Y_test,Y_prediction))

4.672548554009638